### ISSUE TITLE
Milestone Week 3 Day 1 : Application deployment of portfolio project through Github Pages

### ISSUE THREAD

**Issue by usamamaliq** [usamamaliq/Portfolio#7]
Following are the changes made to get the application deployed.

- Setting up the main code in the index.html file.
- Going to repository settings>pages and then selecting master branch for deployment.
- Ensuring HTTPS is enforced.
- Updated Readme file with deployment link.

**Comment by Reem-lab** [comment]
# Hi @usamamaliq,👋🏻👋🏻

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉🔥🔥💯💯
<img src="https://media1.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif"/>


## Highlights ✨✨
📌 Descriptive pull request✅
📌 Great working on the deploy✅
📌 Professional README ✅

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
